networks:
  backend:
    driver: bridge
  default:
    external: true
    name: backend
  frontend:
    driver: bridge
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: docker
    image: mysql:8.0
    networks:
    - backend
    platform: linux/amd64
    ports:
    - 3307:3306
    restart: on-failure
    volumes:
    - database_data_new:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:v1.0.1
    networks:
    - backend
    ports:
    - 1025:1025
    - 8025:8025
  nginx:
    depends_on:
    - php
    environment:
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_SOCKET: tcp://webserver:8707
    image: nginx:latest
    networks:
    - backend
    - frontend
    ports:
    - 8888:80
    - 8707:8707
    restart: on-failure
    user: root
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./:/var/www/html
  php:
    depends_on:
    - database
    - rabbitmq
    - mailhog
    entrypoint:
    - /bin/sh
    - -c
    - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts
      && php-fpm --allow-to-run-as-root
    environment:
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_SOCKET: tcp://webserver:8707
      IN_DOCKER: 'true'
      PHP_IDE_CONFIG: serverName=docker.php.cli
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
    - 9000
    - 9001
    image: ghcr.io/debricked/docker-image-php-xdebug:latest
    networks:
    - backend
    ports:
    - 8000:8000
    restart: on-failure
    shm_size: 2g
    tty: true
    user: root
    volumes:
    - ./:/var/www/html
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: docker
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_ERLANG_COOKIE: rabbitmqcookie
    image: rabbitmq:3.9-management-alpine
    networks:
    - backend
    ports:
    - 5672:5672
    - 15672:15672
    restart: on-failure
    volumes:
    - rabbitmqetc:/etc/rabbitmq/
    - rabbitmqdata:/var/lib/rabbitmq/
    - rabbitmqlogs:/var/log/rabbitmq/
volumes:
  database_data:
    driver: local
  database_data_new:
    driver: local
  rabbitmqdata:
    driver: local
  rabbitmqetc:
    driver: local
  rabbitmqlogs:
    driver: local
